.semver-regxp: &semver-regexp /^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/

stages:
  - lint
  - package

image: registry.srv.local/ci/sb-lua-base:1.0.0

lint:
  stage: lint
  before_script: 
    - luarocks install luacheck
  script:
    - luacheck .
  except:
    - tags

package:
  stage: package
  script:
    - tar czvpf kong-plugin-sb-ab-testing-${CI_COMMIT_REF_NAME}.tar.gz kong/plugins/sb-ab-testing/
    # upload to a storage 
    - luarocks upload kong-plugin-sb-ab-testing-${CI_COMMIT_REF_NAME}.rockspec --api-key=${LUA_ROCKS_API_KEY}
  only:
    - *semver-regexp
